### ISSUE TITLE
Any plans to get this wrapper up on crates.io?

### ISSUE THREAD

**Issue by HeatXD** [spearman/enet-rs#1]
Hello! this enet wrapper seems quite complete and void of needing unsafe code compared to some of the other options i've seen. Are there any plans to get this wrapper up on crates.io?

**Comment by spearman** [comment]
Have you looked at https://github.com/futile/enet-rs (https://crates.io/crates/enet)?

The example client/server doesn't seem to have any unsafe required. It also seems to support generic user data which I haven't implemented in this wrapper.

**Comment by HeatXD** [comment]
Oh! thanks for the pointer
